id: P009604
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1AC248
  title: 'བོན་གྱི་ལྷ་རབས་ལ་དཔྱད་པ། '
  author: ''
  volumes:
    f163a77119b849b1a58e55e9b5f6a0c4:
      image_group_id: I2PD18134
      title: ''
      volume_number: 1
      total_pages: 380
      base_file: v001.txt
