id: IE13C6058
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T19:22:28+00:00'
last_modified: '2022-06-08T12:12:25.361563+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC248
  title: 'བོན་གྱི་ལྷ་རབས་ལ་དཔྱད་པ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    518F:
      image_group_id: I2PD18134
      title: ''
      total_pages: 380
      order: 1
      base_file: 518F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
